---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      register: hostname_output # Hedef sunucularda "hostname -s" çıktısını "hostname_output" değişkenine atar.
...
