---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      # Aşağıdaki gösterim koşulları "AND" ile bağlar. "hostname -s" komutu aşağıdaki iki koşulun sağlandığı sunucularda çalıştırılır.
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution_major_version | int >= 8

...
