---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      register: hostname_output

    - name: Show hostname_output
      debug:
        var: hostname_output.stdout # "hostname_output" değişkeniyle gelen stdout (hostname_output.stdout) değişkenini debug output'a basar.
...
