---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "9" # "hostname -s" komutunu when'de bulunan 2 koşulu sağlayan hedef sunucularda çalıştırır. Koşullu ifade jinja2 formatındadır.
...
