# "Exploring register" task'ının çıktısı "command_register" değişkenine atanır ve "Install patch when changed" task'ı ile "command_register.changed" değişkeni "true" olan sunucularda patch komutu yum ile yüklenir.
# Playbook çıktısındaki "changed" ifadesi playbook'un ilgili sunucuda çalıştığını gösterir. Yani ilk task'ın çalıştığı sunucuların tamamında patch komutu kurulur.
---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution_major_version | int >= 8
      register: command_register

    - name: Install patch when changed
      yum:
        name: patch
        state: present
      when: command_register.changed
...
