
# "item" değişkeni "with_items" ile tanımlanan listedeki tüm değerleri tek tek alır. Task "item" değişkeninin alacağı her değer için bir kez çalışır. 
# Bu örnekte task hedef sunucuların her birinde "james, hayley, lily, anwen" değerleri için toplam 4 kez çalışır. 
---
-
  hosts: linux
  tasks:
    - name: Creating user
      user:
        name: "{{ item }}"
      with_items: 
        - james
        - hayley
        - lily
        - anwen
...
