# "Exploring register" task'ının çıktısı "command_register" değişkenine atanır ve "Show register" task'ı ile debug output'a basılır.
---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution_major_version | int >= 8
      register: command_register

    - name: Show register
      debug:
        var: command_register
...
