---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      when: 
        - ansible_distribution == "CentOS" 
        - ansible_distribution_major_version | int >= 8
      register: command_register

    - name: Install patch when changed
      yum:
        name: patch
        state: present
      when: command_register is changed # "command_register" değişkeninde "changed" değeri true ise "patch" binary'si yüklenir.

    - name: Install patch when skipped
      apt:
        name: patch
        state: present
      when: command_register is skipped # "command_register" değişkeninde "skipped" değeri true ise "patch" binary'si yüklenir.
...
