---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      # "when" direktifinde "or" da kullanılabilir. Hedef sunucularda "or" ile bağlanan koşullardan birisi sağlandığında "hostname -s" komutu çalıştırılır.
      when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version == "9" ) or
            ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "22" )
...
