---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      # jinja2 formatında aşağıdaki gibi matematiksel operatörlerle de koşul yazılabilir.
      when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version | int >= 8 ) or
            ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 22 )
...
