---
-
  hosts: linux
  tasks:
    - name: Exploring register
      command: hostname -s
      register: hostname_output

    - name: Show hostname_output # "hostname_output" değişkenini debug output'a basar.
      debug:
        var: hostname_output
...
